export const SET_SORT_TYPE: "SET_SORT_TYPE" = "SET_SORT_TYPE";
export const SET_SORT_DIRECTION: "SET_SORT_DIRECTION" = "SET_SORT_DIRECTION";
export const SET_SEARCH_TEXT: "SET_SEARCH_TEXT" = "SET_SEARCH_TEXT";
export const SET_ROWS_COUNT: "SET_ROWS_COUNT" = "SET_ROWS_COUNT";
 